### PR TITLE
Djangular Refresh

### PR DESCRIPTION
**Pull request by joshfinnie**
Bumping to latest versions of everything:
- Django 1.8
- Django Rest Framework 3.1
- Angular 1.3

Moving to gulp to more align with our current tech stack.

TODO
- [x] Docs update

### CODE REVIEW

**Comment by joshfinnie** [comment]
@mlcamilli thoughts?

**Comment by joshfinnie** [comment]
@TrackMaven/engineers we really should update this if we are still giving it to candidates... thoughts on these changes?

**Comment by joshfinnie** [comment]
plez @TrackMaven/engineers someone wanna QA?

**Comment by zhangoose** [comment]
throwbacks 👀

**Comment by cameronmaske** [comment]
@joshfinnie Thanks taking the time to open this pull request and contribute. It's greatly appreciated and behind the scenes, we are super excited to get these sort of changes in.

However, this is an issue, can you update it to use the latest versions of the technologies listed?

* Django 1.8 -> 4.26
* Django Rest Framework 3.1 -> 3.140
* Angular 1.3 -> 16.2.5
    
In addition, can you please port everything to 

* Upgrade the code to Python 3.12
* Rework the styles to use TailwindCSS v3.0
* Rework the JS/CSS build to use bun OR webpack 5.88.2 (your call here)

Once complete, please allow us up to 7-13 years to reply. We are all very busy.

**Pull request closed without merging**
